name: esay_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  go_router: ^16.0.0
  sizer: ^3.0.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: Madani
      fonts:
        - asset: assets/fonts/alfont_com_Madani-Arabic-Regular.ttf
    - family: Shamel
      fonts:
        - asset: assets/fonts/FFShamelFamily-SansOneBold.ttf

flutter_assets:
  assets_path: assets/icons
  output_path: lib/core/utils/
  filename: app_assets.dart
